Parsing... [0.010s CPU, 0.020s wall-clock]
Normalizing task... [0.000s CPU, 0.001s wall-clock]
Instantiating...
Generating Datalog program... [0.020s CPU, 0.012s wall-clock]
Normalizing Datalog program...
Normalizing Datalog program: [0.000s CPU, 0.005s wall-clock]
Preparing model... [0.040s CPU, 0.037s wall-clock]
Generated 31 rules.
Computing model... [378.090s CPU, 378.086s wall-clock]
14581888 relevant atoms
57943 auxiliary atoms
14639831 final queue length
29158208 total queue pushes
Completing instantiation... Traceback (most recent call last):
  File "/home/asai/repos/downward/src/translate/translate.py", line 665, in <module>
    main()
  File "/home/asai/repos/downward/src/translate/translate.py", line 655, in main
    sas_task = pddl_to_sas(task)
  File "/home/asai/repos/downward/src/translate/translate.py", line 478, in pddl_to_sas
    reachable_action_params) = instantiate.explore(task)
  File "/home/asai/repos/downward/src/translate/instantiate.py", line 77, in explore
    return instantiate(task, model)
  File "/home/asai/repos/downward/src/translate/instantiate.py", line 55, in instantiate
    for par, arg in zip(parameters, atom.args)])
MemoryError
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/apport_python_hook.py", line 66, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python2.7/dist-packages/apport/__init__.py", line 1, in <module>
    from apport.report import Report
  File "/usr/lib/python2.7/dist-packages/apport/report.py", line 12, in <module>
    import subprocess, tempfile, os.path, urllib, re, pwd, grp, os
  File "/usr/lib/python2.7/subprocess.py", line 432, in <module>
    import pickle
MemoryError

Original exception was:
Traceback (most recent call last):
  File "/home/asai/repos/downward/src/translate/translate.py", line 665, in <module>
    main()
  File "/home/asai/repos/downward/src/translate/translate.py", line 655, in main
    sas_task = pddl_to_sas(task)
  File "/home/asai/repos/downward/src/translate/translate.py", line 478, in pddl_to_sas
    reachable_action_params) = instantiate.explore(task)
  File "/home/asai/repos/downward/src/translate/instantiate.py", line 77, in explore
    return instantiate(task, model)
  File "/home/asai/repos/downward/src/translate/instantiate.py", line 55, in instantiate
    for par, arg in zip(parameters, atom.args)])
MemoryError
