Parsing... [0.010s CPU, 0.015s wall-clock]
Normalizing task... [0.010s CPU, 0.001s wall-clock]
Instantiating...
Generating Datalog program... [0.010s CPU, 0.008s wall-clock]
Normalizing Datalog program...
Normalizing Datalog program: [0.010s CPU, 0.006s wall-clock]
Preparing model... [0.020s CPU, 0.026s wall-clock]
Generated 31 rules.
Computing model... [169.260s CPU, 169.249s wall-clock]
6569361 relevant atoms
37215 auxiliary atoms
6606576 final queue length
13133567 total queue pushes
Completing instantiation... Exception MemoryError: MemoryError() in  ignored
Exception MemoryError: MemoryError() in  ignored
Exception MemoryError: MemoryError() in  ignored
Traceback (most recent call last):
  File "/home/asai/repos/downward/src/translate/instantiate.py", line 57, in instantiate
    fluent_facts, type_to_objects)
  File "/home/asai/repos/downward/src/translate/pddl/actions.py", line 117, in instantiate
    objects_by_type, effects)
  File "/home/asai/repos/downward/src/translate/pddl/effects.py", line 131, in instantiate
    self._instantiate(var_mapping, init_facts, fluent_facts, result)
  File "/home/asai/repos/downward/src/translate/pddl/effects.py", line 139, in _instantiate
    self.literal.instantiate(var_mapping, init_facts, fluent_facts, effects)
MemoryError
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/apport_python_hook.py", line 66, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python2.7/dist-packages/apport/__init__.py", line 1, in <module>
    from apport.report import Report
  File "/usr/lib/python2.7/dist-packages/apport/report.py", line 12, in <module>
    import subprocess, tempfile, os.path, urllib, re, pwd, grp, os
MemoryError

Original exception was:
Traceback (most recent call last):
  File "/home/asai/repos/downward/src/translate/instantiate.py", line 57, in instantiate
    fluent_facts, type_to_objects)
  File "/home/asai/repos/downward/src/translate/pddl/actions.py", line 117, in instantiate
    objects_by_type, effects)
  File "/home/asai/repos/downward/src/translate/pddl/effects.py", line 131, in instantiate
    self._instantiate(var_mapping, init_facts, fluent_facts, result)
  File "/home/asai/repos/downward/src/translate/pddl/effects.py", line 139, in _instantiate
    self.literal.instantiate(var_mapping, init_facts, fluent_facts, effects)
MemoryError
