Parsing... [0.140s CPU, 0.130s wall-clock]
Normalizing task... [0.010s CPU, 0.012s wall-clock]
Instantiating...
Generating Datalog program... [0.010s CPU, 0.014s wall-clock]
Normalizing Datalog program...
Normalizing Datalog program: [0.040s CPU, 0.033s wall-clock]
Preparing model... [0.160s CPU, 0.173s wall-clock]
Generated 31 rules.
Computing model... [70.070s CPU, 70.064s wall-clock]
3170443 relevant atoms
10396 auxiliary atoms
3180839 final queue length
6323507 total queue pushes
Completing instantiation... Traceback (most recent call last):
  File "/home/asai/repos/downward/src/translate/translate.py", line 665, in <module>
    main()
  File "/home/asai/repos/downward/src/translate/translate.py", line 655, in main
    sas_task = pddl_to_sas(task)
  File "/home/asai/repos/downward/src/translate/translate.py", line 478, in pddl_to_sas
    reachable_action_params) = instantiate.explore(task)
  File "/home/asai/repos/downward/src/translate/instantiate.py", line 77, in explore
    return instantiate(task, model)
  File "/home/asai/repos/downward/src/translate/instantiate.py", line 57, in instantiate
    fluent_facts, type_to_objects)
  File "/home/asai/repos/downward/src/translate/pddl/actions.py", line 117, in instantiate
    objects_by_type, effects)
  File "/home/asai/repos/downward/src/translate/pddl/effects.py", line 131, in instantiate
    self._instantiate(var_mapping, init_facts, fluent_facts, result)
  File "/home/asai/repos/downward/src/translate/pddl/effects.py", line 139, in _instantiate
    self.literal.instantiate(var_mapping, init_facts, fluent_facts, effects)
  File "/home/asai/repos/downward/src/translate/pddl/conditions.py", line 340, in instantiate
    atom = Atom(self.predicate, args)
  File "/home/asai/repos/downward/src/translate/pddl/conditions.py", line 279, in __init__
    self.predicate = predicate
MemoryError
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/apport_python_hook.py", line 66, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python2.7/dist-packages/apport/__init__.py", line 1, in <module>
    from apport.report import Report
  File "/usr/lib/python2.7/dist-packages/apport/report.py", line 12, in <module>
    import subprocess, tempfile, os.path, urllib, re, pwd, grp, os
  File "/usr/lib/python2.7/subprocess.py", line 432, in <module>
    import pickle
MemoryError

Original exception was:
Traceback (most recent call last):
  File "/home/asai/repos/downward/src/translate/translate.py", line 665, in <module>
    main()
  File "/home/asai/repos/downward/src/translate/translate.py", line 655, in main
    sas_task = pddl_to_sas(task)
  File "/home/asai/repos/downward/src/translate/translate.py", line 478, in pddl_to_sas
    reachable_action_params) = instantiate.explore(task)
  File "/home/asai/repos/downward/src/translate/instantiate.py", line 77, in explore
    return instantiate(task, model)
  File "/home/asai/repos/downward/src/translate/instantiate.py", line 57, in instantiate
    fluent_facts, type_to_objects)
  File "/home/asai/repos/downward/src/translate/pddl/actions.py", line 117, in instantiate
    objects_by_type, effects)
  File "/home/asai/repos/downward/src/translate/pddl/effects.py", line 131, in instantiate
    self._instantiate(var_mapping, init_facts, fluent_facts, result)
  File "/home/asai/repos/downward/src/translate/pddl/effects.py", line 139, in _instantiate
    self.literal.instantiate(var_mapping, init_facts, fluent_facts, effects)
  File "/home/asai/repos/downward/src/translate/pddl/conditions.py", line 340, in instantiate
    atom = Atom(self.predicate, args)
  File "/home/asai/repos/downward/src/translate/pddl/conditions.py", line 279, in __init__
    self.predicate = predicate
MemoryError
